config/routes.rb
Hieraconfig::Application.routes.draw do
  resources :keys

  resources :keypaths

end

app/models/key.rb
class Key < ActiveRecord::Base
  attr_accessible :name



  # helper method to generate redis keys
  def redis_key(str)
    "user:#{self.id}:#{str}"
  end

end

app/models/keypath.rb
class Keypath < ActiveRecord::Base
  attr_accessible :name

  # find all key in path
  def keys?
    $redis.keys("#{self.name}*")
  end


  def value?(key)
    case $redis.type(key)
      when "string"
        $redis.get(key)
      when "list"
        $redis.lrange(key, 0, -1)
      when "hash"
        $redis.hgetall(key)
    end

  end



  # helper method to generate redis keys
  def redis_key(str)
    "user:#{self.id}:#{str}"
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/keypaths_controller.rb
class KeypathsController < ApplicationController
  # GET /keypaths
  # GET /keypaths.json
  def index
    @keypaths = Keypath.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @keypaths }
    end
  end

  # GET /keypaths/1
  # GET /keypaths/1.json
  def show
    @keypath = Keypath.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @keypath }
    end
  end

  # GET /keypaths/new
  # GET /keypaths/new.json
  def new
    @keypath = Keypath.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @keypath }
    end
  end

  # GET /keypaths/1/edit
  def edit
    @keypath = Keypath.find(params[:id])
  end

  # POST /keypaths
  # POST /keypaths.json
  def create
    @keypath = Keypath.new(params[:keypath])

    respond_to do |format|
      if @keypath.save
        format.html { redirect_to @keypath, :notice => 'Keypath was successfully created.' }
        format.json { render :json => @keypath, :status => :created, :location => @keypath }
      else
        format.html { render :action => "new" }
        format.json { render :json => @keypath.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /keypaths/1
  # PUT /keypaths/1.json
  def update
    @keypath = Keypath.find(params[:id])

    respond_to do |format|
      if @keypath.update_attributes(params[:keypath])
        format.html { redirect_to @keypath, :notice => 'Keypath was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @keypath.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /keypaths/1
  # DELETE /keypaths/1.json
  def destroy
    @keypath = Keypath.find(params[:id])
    @keypath.destroy

    respond_to do |format|
      format.html { redirect_to keypaths_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/keys_controller.rb
class KeysController < ApplicationController
  # GET /keys
  # GET /keys.json
  def index
    @keys = Key.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @keys }
    end
  end

  # GET /keys/1
  # GET /keys/1.json
  def show
    @key = Key.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @key }
    end
  end

  # GET /keys/new
  # GET /keys/new.json
  def new
    @key = Key.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @key }
    end
  end

  # GET /keys/1/edit
  def edit
    @key = Key.find(params[:id])
  end

  # POST /keys
  # POST /keys.json
  def create
    @key = Key.new(params[:key])

    respond_to do |format|
      if @key.save
        format.html { redirect_to @key, :notice => 'Key was successfully created.' }
        format.json { render :json => @key, :status => :created, :location => @key }
      else
        format.html { render :action => "new" }
        format.json { render :json => @key.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /keys/1
  # PUT /keys/1.json
  def update
    @key = Key.find(params[:id])

    respond_to do |format|
      if @key.update_attributes(params[:key])
        format.html { redirect_to @key, :notice => 'Key was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @key.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /keys/1
  # DELETE /keys/1.json
  def destroy
    @key = Key.find(params[:id])
    @key.destroy

    respond_to do |format|
      format.html { redirect_to keys_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keypaths_helper.rb
module KeypathsHelper
end

app/helpers/keys_helper.rb
module KeysHelper
end

app/views/keypaths/_form.html.erb
<%= form_for @keypath, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                keypaths_path, :class => 'btn' %>
  </div>
<% end %>

app/views/keypaths/edit.html.erb
<%- model_class = Keypath -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/keypaths/index.html.erb
<%- model_class = Keypath -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @keypaths.each do |keypath| %>
      <tr>
        <td><%= link_to keypath.name, keypath_path(keypath) %></td>
        <td><%= keypath.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_keypath_path(keypath), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      keypath_path(keypath),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_keypath_path,
            :class => 'btn btn-primary' %>

app/views/keypaths/new.html.erb
<%- model_class = Keypath -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/keypaths/show.html.erb
<%- model_class = Keypath -%>
<div class="page-header">
  <h1><%=t '.title', :default => @keypath.name.gsub(':', '/') %>/</h1>
</div>

<%- @keypath.keys?.each do |key|%>
<dl class="dl-horizontal">
  <dt><strong><%= key.split(':').last %>:</strong></dt>
  <dd><pre><%= @keypath.value?(key) %></pre></dd>
</dl>
<% end %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              keypaths_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_keypath_path(@keypath), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              keypath_path(@keypath),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/keys/_form.html.erb
<%= form_for(@key) do |f| %>
  <% if @key.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@key.errors.count, "error") %> prohibited this key from being saved:</h2>

      <ul>
      <% @key.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keys/edit.html.erb
<h1>Editing key</h1>

<%= render 'form' %>

<%= link_to 'Show', @key %> |
<%= link_to 'Back', keys_path %>

app/views/keys/index.html.erb
<h1>Listing keys</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @keys.each do |key| %>
  <tr>
    <td><%= key.name %></td>
    <td><%= link_to 'Show', key %></td>
    <td><%= link_to 'Edit', edit_key_path(key) %></td>
    <td><%= link_to 'Destroy', key, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Key', new_key_path %>

app/views/keys/new.html.erb
<h1>New key</h1>

<%= render 'form' %>

<%= link_to 'Back', keys_path %>

app/views/keys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @key.name %>
</p>


<%= link_to 'Edit', edit_key_path(@key) %> |
<%= link_to 'Back', keys_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hieraconfig</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>